name: Build docs

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: false
        documentation_path: './docs/source'
        requirements_path: './requeriments_docs.txt'
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}
