name: Build docs

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: py-actions/py-dependency-install@v3
      with:
        path: "./requirements.txt"
        update-pip: "false"
        update-setuptools: "false"
        update-wheel: "false"
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        documentation_path: './docs/source'
        requirements_path: './requeriments_docs.txt'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages